version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\Masterminds\semver
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
  - x64

install:
  - go version
  - go env

test_script:
  - go test -v
